cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
