cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'ruby-build'
brew 'rbenv'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

cask 'atom'
cask 'firefox'
cask 'google-chrome'
